"""Add items_failed and error_notes to ingestion_runs

Revision ID: 8bfeb200e9f5
Revises: e2e0c4edd175
Create Date: 2025-08-12 18:38:45.060706

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8bfeb200e9f5"
down_revision = "e2e0c4edd175"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ingestion_runs", sa.Column("items_failed", sa.Integer(), nullable=False, server_default="0"))
    op.add_column("ingestion_runs", sa.Column("error_notes", sa.String(length=1000), nullable=True))
    op.alter_column("ingestion_runs", "items_processed", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("ingestion_runs", "items_new", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("ingestion_runs", "items_updated", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("ingestion_runs", "errors_count", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("ingestion_runs", "status", existing_type=sa.VARCHAR(length=20), nullable=False)
    op.alter_column("ingestion_runs", "notes", existing_type=postgresql.JSON(astext_type=sa.Text()), nullable=False)
    op.alter_column("sources", "rate_limit", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("sources", "config", existing_type=postgresql.JSON(astext_type=sa.Text()), nullable=False)
    op.alter_column("sources", "is_active", existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("sources", "is_active", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("sources", "config", existing_type=postgresql.JSON(astext_type=sa.Text()), nullable=True)
    op.alter_column("sources", "rate_limit", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("ingestion_runs", "notes", existing_type=postgresql.JSON(astext_type=sa.Text()), nullable=True)
    op.alter_column("ingestion_runs", "status", existing_type=sa.VARCHAR(length=20), nullable=True)
    op.alter_column("ingestion_runs", "errors_count", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("ingestion_runs", "items_updated", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("ingestion_runs", "items_new", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("ingestion_runs", "items_processed", existing_type=sa.INTEGER(), nullable=True)
    op.drop_column("ingestion_runs", "error_notes")
    op.drop_column("ingestion_runs", "items_failed")
    # ### end Alembic commands ###
