"""Add indexes to ingestion_runs table for performance

Revision ID: d5e84b9df44d
Revises: 8bfeb200e9f5
Create Date: 2025-08-13 11:48:49.492722

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d5e84b9df44d"
down_revision = "8bfeb200e9f5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ingestion_runs",
        "items_failed",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.create_index(
        "ix_ingestion_runs_source_id_started_at_desc",
        "ingestion_runs",
        ["source_id", sa.literal_column("started_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_ingestion_runs_status_started_at_desc",
        "ingestion_runs",
        ["status", sa.literal_column("started_at DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_ingestion_runs_status_started_at_desc", table_name="ingestion_runs")
    op.drop_index("ix_ingestion_runs_source_id_started_at_desc", table_name="ingestion_runs")
    op.alter_column(
        "ingestion_runs",
        "items_failed",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
